import { DataDto } from "../../../types";
import { LoadIconConfig } from "./render-static-grid-icon";

export const getNonEssentialIconConfigs = (data: DataDto): LoadIconConfig[] => [
	// Main Non-Essential Icon (Centered) - Shown when nonessentialLoads === 0
	{
		id: "noness_default",
		x: 320,
		y: 339,
		width: 38,
		height: 38,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition:
			data.iconNonessentialLoad1 === "default" &&
			data.iconNonessentialLoad2 === "default",
		iconType: "nonEss",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 24,
	},
	{
		id: "noness_default",
		x: 303.5,
		y: 305.5,
		width: 70,
		height: 70,
		displayCondition:
			!data.showNonessential || [1, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.nonessentialIcon === "default",
		iconType: "nonEss",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 24,
	},
	{
		id: "noness_oven",
		x: 303.5,
		y: 305.5,
		width: 70,
		height: 70,
		displayCondition:
			!data.showNonessential || [1, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.nonessentialIcon === "oven",
		iconType: "oven",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 32,
	},
	{
		id: "noness_boiler",
		x: 303.5,
		y: 305.5,
		width: 70,
		height: 70,
		displayCondition:
			!data.showNonessential || [1, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.nonessentialIcon === "boiler",
		iconType: "boiler",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 24,
	},
	{
		id: "noness_pump",
		x: 303.5,
		y: 305.5,
		width: 70,
		height: 70,
		displayCondition:
			!data.showNonessential || [1, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.nonessentialIcon === "pump",
		iconType: "pump",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 24,
	},
	{
		id: "noness_ac",
		x: 311,
		y: 312,
		width: 55,
		height: 55,
		displayCondition:
			!data.showNonessential || [1, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.nonessentialIcon === "aircon",
		iconType: "aircon",
		prefix: "noness",
		dynamicColor: data.gridColour,
		viewBoxSize: 24,
	},

	// Split View Icons (Left/Right) - Shown when nonessentialLoads >= 1
	{
		id: "noness_default_left",
		x: 306,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition:
			data.iconNonessentialLoad1 === "default" &&
			data.iconNonessentialLoad2 !== "default",
		iconType: "nonEss",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness_default_right",
		x: 343,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition:
			data.iconNonessentialLoad1 !== "default" &&
			data.iconNonessentialLoad2 === "default",
		iconType: "nonEss",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad2,
		viewBoxSize: 24,
	},
	// Boiler Icons
	{
		id: "noness_boiler_left",
		x: 306,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "boiler",
		iconType: "boiler",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness_boiler_right",
		x: 343,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad2 === "boiler",
		iconType: "boiler",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad2,
		viewBoxSize: 24,
	},
	// Pump Icons
	{
		id: "noness_pump_left",
		x: 306,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "pump",
		iconType: "pump",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness_pump_right",
		x: 343,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad2 === "pump",
		iconType: "pump",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad2,
		viewBoxSize: 24,
	},
	// Oven Icons
	{
		id: "noness_oven_left",
		x: 306,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "oven",
		iconType: "oven",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 32,
	},
	{
		id: "noness_oven_right",
		x: 343,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad2 === "oven",
		iconType: "oven",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad2,
		viewBoxSize: 32,
	},
	// AC Icons
	{
		id: "noness_ac_left",
		x: 308,
		y: 345,
		width: 25,
		height: 25,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "aircon",
		iconType: "aircon",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness_ac_right",
		x: 345,
		y: 345,
		width: 25,
		height: 25,
		displayCondition:
			!data.showNonessential || [0, 1].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad2 === "aircon",
		iconType: "aircon",
		prefix: "noness",
		dynamicColor: data.dynamicColourNonEssentialLoad2,
		viewBoxSize: 24,
	},
	// Additional Non-Essential Load Icons
	{
		id: "noness1_default",
		x: 324.5,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "default",
		iconType: "nonEss",
		prefix: "noness1",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness1_boiler",
		x: 324.5,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "boiler",
		iconType: "boiler",
		prefix: "noness1",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness1_pump",
		x: 324.5,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "pump",
		iconType: "pump",
		prefix: "noness1",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
	{
		id: "noness1_oven",
		x: 324.5,
		y: 341,
		width: 32,
		height: 32,
		displayCondition:
			!data.showNonessential || [0, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "oven",
		iconType: "oven",
		prefix: "noness1",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 32,
	},
	{
		id: "noness1_ac",
		x: 326.5,
		y: 345,
		width: 25,
		height: 25,
		displayCondition:
			!data.showNonessential || [0, 2, 3].includes(data.nonessentialLoads),
		opacityCondition: data.iconNonessentialLoad1 === "aircon",
		iconType: "aircon",
		prefix: "noness1",
		dynamicColor: data.dynamicColourNonEssentialLoad1,
		viewBoxSize: 24,
	},
];
