name: Bug report
description: File a bug report
labels: ['type/bug']
body:
  - type: markdown
    attributes:
      value: |
        **NOTE:** Before you start, the following should be completed.

        - Read the documentation to ensure the correct setup.
        - Make sure no [similar issues(including closed ones)](https://github.com/slipx06/sunsynk-power-flow-card/issues?q=is%3Aissue+is%3Aopen+label%3Atype%2Fbug) exists.
        - Make sure the request is based on the latest release.

        Thanks for taking the time to assist with improving this project!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A concise description of what you expected to happen.
      placeholder: Tell us what you should see!
    validations:
      required: true
  - type: input
    id: card-version
    attributes:
      label: Card Version
      description: The version of the card you have installed
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: The version of Home Assistant you have installed
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please copy and paste your configuration. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
